### ISSUE TITLE
Incorrect camouflage order for Fennec 45

### ISSUE THREAD

**Issue by carlssonemil** [carlssonemil/orion#12]
The camouflage order on the Fennec 45 is incorrect. The camouflage "2087" is first when it should be last. Probably related to the way object keys are sorted by default in JavaScript.

![Screenshot 2022-11-09 at 00 10 38](https://user-images.githubusercontent.com/10532336/200695884-3cc334c2-c308-43f4-9d6f-4315678aa1c9.gif)

**Comment by sol3uk** [comment]
**_Note for posterity:_**
This is regarding an issue with how we store camo names, since they are used as object keys in javascript (little bit naughty), and since this camo is totally numeric, it will get re-ordered when accessed in memory, this is usually not an issue but as we want to retain the ordering of the camos, this is where it becomes an issue. 
This potential fixes for this range from "hacky" (see my hacky suggested fix above) to a downright redo of the data structure. Hopefully there's a nice middle ground somewhere that doesn't add too much extra code, fixes this specific case, whilst maintains the structure of the local storage data and allows more camos to be added in the future and not have to do any extra code to maintain the order of the new camos as well 😄
