### ISSUE TITLE
Counting individual camos towards Orion progress

### ISSUE THREAD

**Issue by EvilAngel00** [carlssonemil/orion#18]
Hey Emil,

I used your tracker for Damascus back in the day and I'm enjoying it a lot also with the Orion grind. At the moment I'm only levelling up the guns while focusing on the first 2-3 camos so I don't finish all of them before moving on to the next gun. I noticed that the Orion progress bar doesn't update by just finishing regular camos but only when finishing the gold/plat/poly camo. Is it intended? 

It would feel more satisfying to see the progress go up by smaller increments whenever a camo is unlocked, what do you think? 😄

Thank you for your work on this! (and the other contributors!)

**Comment by carlssonemil** [comment]
Hey!

Glad to hear that you enjoy my trackers! 😄 

It's currently intended to be counted that way. I haven't figured out a way to count individual camouflages towards the progress without encountering false positives issues. Right now, before DLC weapons are added, it's fairly easy to count the individual progress, but let me paint you a picture of the dilemma I've been faced with ever since Call of Duty Cold War (2020) - when they began counting DLC weapons towards the mastery camouflage progress 😅:

Let's say we need 8 Gold camouflages for the Assault Rifles category, with there being 10 weapons in total (8 base game and 2 DLC weapons). You would need to complete 32 (8 * 4) base camouflages to be considered completed with this category, right? But since there's 40 camouflages in total, counting the base game rifles and DLC rifles, you could potentially finish 2 camouflages on 1 rifle and 2 on another, which in the calculation would sum up to one completed rifle, when both are just half-completed. This could then down the road potentially make the Orion progress 100%, when in reality you still have a few weapons left. It's a bit hard to explain, but I hope my point, and dilemma, was clear enough 😄 

The Damascus grind was so much easier to calculate, since DLC weapons did not count.

I've spent a lot of hours trying to fix this issue but haven't come up with a viable solution yet 🤔 I'll leave this issue open and try my hand at it again sometime when I have the time. But anyone that's willing is very much free to try and find a solution to this 😄

**Comment by EvilAngel00** [comment]
I see, thanks for the explanation!

I'm not very familiar with how to implement this but in terms of raw ideas, since we know how many guns are need per category (let's say n) to complete the Orion challenge, can't we group them, sort by how many camos are unlocked on a gun and take the first n guns?

Doing this for every category, you would always end up with the 51 guns with the most progress and starting a DLC gun would not count towards the progress until you unlock more camos than any existing one.

**Comment by carlssonemil** [comment]
That's actually a pretty smart idea! 🤔 I'll see if I can convert the idea into code some time this week!

**Comment by sol3uk** [comment]
> sort by how many camos are unlocked on a gun and take the first n guns?

100% agree, this is how I would implement it as well 😄
