### ISSUE TITLE
Minimal mode

### ISSUE THREAD

**Issue by emorygg** [carlssonemil/orion#28]
It would be convenient to be able to see all the categories and guns at once, Something similar to the attached image. Other than that the website is a great tool to have for the camo grind, thank you very much for making it and everyone that has helped improve it!
![image](https://user-images.githubusercontent.com/36583346/202869700-ac6271bf-78fd-4477-9097-22e97598204a.png)

**Comment by carlssonemil** [comment]
Sort of like a compressed version of the UI? I can look into it! 😄

**Comment by sol3uk** [comment]
I'm going to have a crack at this as I have an idea on how this could be the weapons page version of the "list" view where it's essentially just a more compact version similar to what we have here where the camos are listed in a column below the weapon with the challenge next to it

**Comment by sol3uk** [comment]
It's tricky to get it as compact as it is above, since we track mastery camos individually on each gun.
Here's what I have so far though. I tried reducing the font size a bit (I don't want to go too small)
I'm hoping if we can reduce down and refactor the challenge text, maybe give a choice of fully qualified text challenges or shortened wording (i.e. get rid of all the "Get" this, "while" that, and all the extra babble in between and on the end), then I might be able to get them all to 1 line. 

Thoughts @carlssonemil?

![image](https://user-images.githubusercontent.com/26093813/204026822-591e4885-c733-461c-a166-056c1d923279.png)

I could also maybe try putting all the mastery camos on one line to reduce vertical space. 
Like this (BEWARE, awful mockup incoming):

![image](https://user-images.githubusercontent.com/26093813/204028292-2a5fbde2-c757-479d-b8bf-943b26d2cd4f.png)

**Comment by carlssonemil** [comment]
We could decrease the padding around the requirement. What font size is it currently? I think we go a bit smaller 👍 And yeah, we can definitely remove the redundant "babble" in the requirement. Preferably we would have a function where we can pass a parameter if we want a compact text or a descriptive one which returns the requirement.

Great job! Looks good! 😄

**Comment by sol3uk** [comment]
It's only 2px top and bottom lol 😆 
Thought I'd go as small as possible without it looking too close to the edge

**Comment by sol3uk** [comment]
I'll definitely reduce the weapon padding as well , squeeze as much space out of it as I can without ruining the design integrity

**Comment by sol3uk** [comment]
Oh the padding on the sides, yep I can reduce that!

**Comment by sol3uk** [comment]
Just FYI @emorygg, we pushed a new feature as part of #33 that hopefully helps with what you were after?
Hope you enjoy!
