### ISSUE TITLE
Completion dialog shows UTC epoch as start date

### ISSUE THREAD

**Issue by florensie** [carlssonemil/orion#30]
![image](https://user-images.githubusercontent.com/13403842/202916174-2a66bc29-c35b-406e-bd1d-bd5af29e55e5.png)

> 19317 days ago on 1/1/1970

**Comment by carlssonemil** [comment]
Hm.. Odd. It seems to be working for me! I'll look into it!

**Comment by sol3uk** [comment]
Replicated on Brave private browsing.
Local storage shows the date correctly, no errors in console, could be a parsing issue?

![image](https://user-images.githubusercontent.com/26093813/204152082-50dbc470-3178-4069-9e97-a78db0646d9e.png)

**Comment by sol3uk** [comment]
Done a little investigation on this, seems like the `this.beganGrind` gets evaluation on application startup, this means that it will be initially null if its your first visit. When you pass null to the date constructor `new Date(null)` we get the unix start stamp as shown above. A fix for this would be for the date to be re-evaluated before the modal is shown.

**Comment by sol3uk** [comment]
Since the user can only encounter this error when the session is left open (any refresh after marking one bit of camo progress), a new date to fill in for the null `beganGrind` variable should be fine as a fix for this. 
Alternatively could we maybe lazy load modal component? 
I'm not sure what you would need to do to refresh the `beganGrind` state variable?

![image](https://user-images.githubusercontent.com/26093813/204154165-8d68e960-6661-49f0-b43e-49f7bc3696a9.png)

**Comment by carlssonemil** [comment]
We could extract the modal into its own component which fetches the `beganGrind` state variable upon mount, but I think your fix in #36 should be fine for now! 😄
