### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chumbawvmba** [carlssonemil/orion#53]
Seems to be tracking weapons that are not required within the progress bar now

I.e. If I complete 4/4 snipers the 5th sniper should not count towards my overall progress bar, but it currently is. Effectively lowering the overall progress % because it's counting more weapons than necessary.

Great work though, used this thing a couple years in a row now and love it every year.

**Comment by carlssonemil** [comment]
This is not a bug, but an intended feature 😄 Due to the way the camouflage system is implemented, essentially you need a total of 51 Polyatomic camouflages to unlock the Orion camouflage - but they don't cap for each category. So in theory, you could soon completely skip the melee and launchers category and instead get Polyatomic for DLC weapons in other categories, all counting towards the total progress.

Once you unlock 51 Polyatomic camouflages on the site, the percentage will be 100% (or it should be at least, by my testing 😅)

See this closed issue for more details:
- #31

**Comment by florensie** [comment]
> Once you unlock 51 Polyatomic camouflages on the site, the percentage will be 100% (or it should be at least, by my testing 😅)

I actually just found out this isn't true:
![image](https://user-images.githubusercontent.com/13403842/207424345-29a89a57-d8dc-47f8-82f7-c19a9a21fe6c.png)
