### ISSUE TITLE
Suggestion[integration]

### ISSUE THREAD

**Issue by isiikz** [carlssonemil/orion#66]
it would be nice to have a OBS integration so Streamer can show there camo grind while streaming <3 or a discord bot <3

love your work man <3

**Comment by carlssonemil** [comment]
While I agree that it would be a nice feature, I'm pretty sure it's impossible with the way the data is currently stored in the app.

I use the web browser's native storage ([localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)) to store all the progress. Making it so that you don't need an account to use the app, simply browse to it and start tracking. The data is therefore not accessible outside of the web browser. To be able to access the data from an external source we would have to build a database and have each user log in with an account instead. 

I'll definitely note it down as a possible feature for the next (inevitable) tracker. But for this current tracker I'll unfortunately have to say no 😞
